# Generated by Django 3.1.4 on 2020-12-13 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rover', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='environment',
            name='humidity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='environment',
            name='temperature',
            field=models.IntegerField(default=0),
        ),
    ]
