# Generated by Django 3.1.4 on 2020-12-13 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rover', '0003_rover'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Rover',
            new_name='RoverDesc',
        ),
    ]
