# Generated by Django 3.1.4 on 2020-12-13 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rover', '0004_auto_20201213_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='environment',
            name='solar_flare',
            field=models.BooleanField(choices=[(True, 'true'), (False, 'false')]),
        ),
        migrations.AlterField(
            model_name='environment',
            name='storm',
            field=models.BooleanField(choices=[(True, 'true'), (False, 'false')]),
        ),
    ]
