# Generated by Django 3.1.4 on 2020-12-13 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rover', '0005_auto_20201213_2110'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoverMovement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('up', 'up'), ('down', 'down'), ('left', 'left'), ('right', 'right')], max_length=100)),
            ],
        ),
    ]
