# Generated by Django 3.1.4 on 2020-12-13 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rover', '0006_rovermovement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roverdesc',
            name='inventory_quantity',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3)]),
        ),
    ]
