# Generated by Django 3.1.4 on 2020-12-13 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rover', '0007_auto_20201214_0249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roverdesc',
            name='inventory_type',
            field=models.CharField(choices=[('storm_shield', 'storm_shield'), ('water_sample', 'water_sample'), ('rock_sample', 'rock_sample')], max_length=100),
        ),
    ]
